version: '3.1'

services:
  drupal:
    image: drupal:9
        
    ports:
     - 8080:80
  postgres: 
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD = assman
    restart: always